#oauth-server
server:
  port: 9009
spring:
  application:
    name: bjsxt-oauth-server
#dubbo
dubbo:
  application:
    name: bjsxt-oauth-server
  registry:
    address: zookeeper://106.75.190.206:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20884
  consumer:
    check: false
  config-center:
    timeout: 10000
